/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sneakerFour.glb
Author: Akinaro (https://sketchfab.com/Akinaro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rtfktchallenge-class-ic-rtfkt-b9cfddf111e649598a4f217a8d5c38e2
Title: #RTFKTChallenge - "Class-IC" RTFKT
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function  Model(props) {
  const { nodes, materials } = useGLTF('/sneakerFour.glb')
  return (
    <group {...props} dispose={null} scale={100}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.blinn6SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.blinn4SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.bladeblinn31SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.blinn1SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.blinn7SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.blinn5SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/sneakerFour.glb')
