/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Sneaker.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sneaker.glb')
  return (
    <group {...props} rotation={[3.1, 0.00, 0.00]}
    scale={0.1} >
      <mesh geometry={nodes.Mesh_0_bladeblinn31SG_0.geometry} material={nodes.Mesh_0_bladeblinn31SG_0.material} />
      <mesh geometry={nodes.Mesh_1_blinn6SG_0.geometry} material={nodes.Mesh_1_blinn6SG_0.material} />
      <mesh geometry={nodes.Mesh_2_blinn7SG_0.geometry} material={nodes.Mesh_2_blinn7SG_0.material} />
      <mesh geometry={nodes.Mesh_4_blinn1SG002_0.geometry} material={nodes.Mesh_4_blinn1SG002_0.material} />
      <mesh geometry={nodes.Mesh_5_blinn2SG_0.geometry} material={nodes.Mesh_5_blinn2SG_0.material} />
      <mesh geometry={nodes.Mesh_6_blinn2SG001_0.geometry} material={nodes.Mesh_6_blinn2SG001_0.material} />
      <mesh geometry={nodes.Mesh_7_blinn2SG_0.geometry} material={nodes.Mesh_7_blinn2SG_0.material} />
      <mesh geometry={nodes.Mesh_8_blinn3SG_0.geometry} material={nodes.Mesh_8_blinn3SG_0.material} />
      <mesh geometry={nodes.Mesh_9_blinn4SG_0.geometry} material={nodes.Mesh_9_blinn4SG_0.material} />
      <mesh geometry={nodes.Mesh_10_blinn5SG_0.geometry} material={nodes.Mesh_10_blinn5SG_0.material} />
    </group>
  )
}

useGLTF.preload('/sneaker.glb')
