/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sneakerOne.glb
Author: MS-3D (https://sketchfab.com/MS-3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rtfkt-challenge-retro-freestyle-punk-bd9c6a35e67d4b7484f862c5870b4c36
Title: RTFKT Challenge - Retro Freestyle Punk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sneakerOne.glb')
  return (
    <group {...props} dispose={null} scale={100}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material-A']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material-B']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material-C']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material-D']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material-E']} />
      </group>
    </group>
  )
}

useGLTF.preload('/sneakerOne.glb')
