/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 thinking.gltf
Author: Ricardo Sanchez (https://sketchfab.com/380660711785)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/thinking-emoji-149e21aa8901486a9317df4657407182
Title: Thinking emoji
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const Ref = useRef();
  useFrame(state => (Ref.current.rotation.y = Math.sin(state.clock.elapsedTime)*0.1))
  const { nodes, materials } = useGLTF('/thinking.gltf')
  return (
    <group {...props} dispose={null}>
      <group ref={Ref} scale={0.02}>
        <mesh geometry={nodes.Object_Material_0.geometry} 
        material={materials.Material} 
        position={[-0.05, 3.11, 0]} 
        rotation={[-Math.PI / 2.2, 0, 0]} 
        scale={108.34} />
      </group>
    </group>
  )
}

useGLTF.preload('/thinking.gltf')
