/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sneakerThree.glb
Author: Berk Gedik (https://sketchfab.com/berkgedik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rtfktchallenge-paul-theme-tekken-70359e9596354126b3fa791d342276ab
Title: #RTFKTChallenge - Paul Theme (Tekken)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sneakerThree.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh geometry={nodes['rtfkt_aj1007_01-Sole_0'].geometry} material={materials['01-Sole']} />
        <mesh geometry={nodes['rtfkt_aj1007_01-Sole_0_1'].geometry} material={materials['01-Sole']} />
      </group>
      <group scale={100}>
        <mesh geometry={nodes['rtfkt_aj1011_06-Side_0'].geometry} material={materials.material_0} />
        <mesh geometry={nodes['rtfkt_aj1011_06-Side_0_1'].geometry} material={materials.material_0} />
      </group>
      <mesh geometry={nodes['rtfkt_aj1006_05-High_0'].geometry} material={materials['05-High']} scale={100} />
      <mesh geometry={nodes['rtfkt_aj1008_02-Mid_0'].geometry} material={materials['02-Mid']} scale={100} />
      <mesh geometry={nodes['rtfkt_aj1009_04-One_0'].geometry} material={materials['04-One']} scale={100} />
      <mesh geometry={nodes['rtfkt_aj1010_03-Top_0'].geometry} material={materials['03-Top']} scale={100} />
    </group>
  )
}

useGLTF.preload('/sneakerThree.glb')
